name: halo_music
description: "A Music Player, Build With Flutter."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Audio Stack
  just_audio: ^0.9.42         
  audio_service: ^0.18.17      
  on_audio_query: ^2.9.0       
  
  # Utils
  provider: ^6.1.1
  permission_handler: ^11.3.0
  intl: ^0.20.2
  font_awesome_flutter: ^10.7.0
  rxdart: ^0.27.7 
  path_provider: ^2.1.2
  dynamic_color: ^1.8.1
  headphones_detection: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true
  generate: true

assets:
 - assets/